// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8BjTJ-8Aaqaub55j7wyn4_9tKy9mhcM8',
    appId: '1:854817893161:web:eda8d551fbfe9ac6eee538',
    messagingSenderId: '854817893161',
    projectId: 'caretutors-eab79',
    authDomain: 'caretutors-eab79.firebaseapp.com',
    storageBucket: 'caretutors-eab79.firebasestorage.app',
    measurementId: 'G-ZP3WC1NDB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5IMuw1xJ0k5UWPobfC-P4VQjJ7h9oGvI',
    appId: '1:854817893161:android:e6aa97058a800a5eeee538',
    messagingSenderId: '854817893161',
    projectId: 'caretutors-eab79',
    storageBucket: 'caretutors-eab79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTOk9nr2x_NCwRfyRJIeEZ4viYuEjF1EU',
    appId: '1:854817893161:ios:204e7f01c1f3f516eee538',
    messagingSenderId: '854817893161',
    projectId: 'caretutors-eab79',
    storageBucket: 'caretutors-eab79.firebasestorage.app',
    iosBundleId: 'com.example.caretutors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTOk9nr2x_NCwRfyRJIeEZ4viYuEjF1EU',
    appId: '1:854817893161:ios:204e7f01c1f3f516eee538',
    messagingSenderId: '854817893161',
    projectId: 'caretutors-eab79',
    storageBucket: 'caretutors-eab79.firebasestorage.app',
    iosBundleId: 'com.example.caretutors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8BjTJ-8Aaqaub55j7wyn4_9tKy9mhcM8',
    appId: '1:854817893161:web:6de7c177a45753f1eee538',
    messagingSenderId: '854817893161',
    projectId: 'caretutors-eab79',
    authDomain: 'caretutors-eab79.firebaseapp.com',
    storageBucket: 'caretutors-eab79.firebasestorage.app',
    measurementId: 'G-DXLVL5BDEV',
  );
}
